// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/grpc/testing/services.proto

#ifndef PROTOBUF_src_2fproto_2fgrpc_2ftesting_2fservices_2eproto__INCLUDED
#define PROTOBUF_src_2fproto_2fgrpc_2ftesting_2fservices_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "src/proto/grpc/testing/messages.pb.h"
#include "src/proto/grpc/testing/control.pb.h"
#include "src/proto/grpc/testing/stats.pb.h"
// @@protoc_insertion_point(includes)
namespace grpc {
namespace testing {
class BoolValue;
class BoolValueDefaultTypeInternal;
extern BoolValueDefaultTypeInternal _BoolValue_default_instance_;
class ChannelArg;
class ChannelArgDefaultTypeInternal;
extern ChannelArgDefaultTypeInternal _ChannelArg_default_instance_;
class ClientArgs;
class ClientArgsDefaultTypeInternal;
extern ClientArgsDefaultTypeInternal _ClientArgs_default_instance_;
class ClientConfig;
class ClientConfigDefaultTypeInternal;
extern ClientConfigDefaultTypeInternal _ClientConfig_default_instance_;
class ClientStats;
class ClientStatsDefaultTypeInternal;
extern ClientStatsDefaultTypeInternal _ClientStats_default_instance_;
class ClientStatus;
class ClientStatusDefaultTypeInternal;
extern ClientStatusDefaultTypeInternal _ClientStatus_default_instance_;
class ClosedLoopParams;
class ClosedLoopParamsDefaultTypeInternal;
extern ClosedLoopParamsDefaultTypeInternal _ClosedLoopParams_default_instance_;
class CoreRequest;
class CoreRequestDefaultTypeInternal;
extern CoreRequestDefaultTypeInternal _CoreRequest_default_instance_;
class CoreResponse;
class CoreResponseDefaultTypeInternal;
extern CoreResponseDefaultTypeInternal _CoreResponse_default_instance_;
class EchoStatus;
class EchoStatusDefaultTypeInternal;
extern EchoStatusDefaultTypeInternal _EchoStatus_default_instance_;
class HistogramData;
class HistogramDataDefaultTypeInternal;
extern HistogramDataDefaultTypeInternal _HistogramData_default_instance_;
class HistogramParams;
class HistogramParamsDefaultTypeInternal;
extern HistogramParamsDefaultTypeInternal _HistogramParams_default_instance_;
class LoadParams;
class LoadParamsDefaultTypeInternal;
extern LoadParamsDefaultTypeInternal _LoadParams_default_instance_;
class Mark;
class MarkDefaultTypeInternal;
extern MarkDefaultTypeInternal _Mark_default_instance_;
class Payload;
class PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class PoissonParams;
class PoissonParamsDefaultTypeInternal;
extern PoissonParamsDefaultTypeInternal _PoissonParams_default_instance_;
class ReconnectInfo;
class ReconnectInfoDefaultTypeInternal;
extern ReconnectInfoDefaultTypeInternal _ReconnectInfo_default_instance_;
class ReconnectParams;
class ReconnectParamsDefaultTypeInternal;
extern ReconnectParamsDefaultTypeInternal _ReconnectParams_default_instance_;
class RequestResultCount;
class RequestResultCountDefaultTypeInternal;
extern RequestResultCountDefaultTypeInternal _RequestResultCount_default_instance_;
class ResponseParameters;
class ResponseParametersDefaultTypeInternal;
extern ResponseParametersDefaultTypeInternal _ResponseParameters_default_instance_;
class Scenario;
class ScenarioDefaultTypeInternal;
extern ScenarioDefaultTypeInternal _Scenario_default_instance_;
class ScenarioResult;
class ScenarioResultDefaultTypeInternal;
extern ScenarioResultDefaultTypeInternal _ScenarioResult_default_instance_;
class ScenarioResultSummary;
class ScenarioResultSummaryDefaultTypeInternal;
extern ScenarioResultSummaryDefaultTypeInternal _ScenarioResultSummary_default_instance_;
class Scenarios;
class ScenariosDefaultTypeInternal;
extern ScenariosDefaultTypeInternal _Scenarios_default_instance_;
class SecurityParams;
class SecurityParamsDefaultTypeInternal;
extern SecurityParamsDefaultTypeInternal _SecurityParams_default_instance_;
class ServerArgs;
class ServerArgsDefaultTypeInternal;
extern ServerArgsDefaultTypeInternal _ServerArgs_default_instance_;
class ServerConfig;
class ServerConfigDefaultTypeInternal;
extern ServerConfigDefaultTypeInternal _ServerConfig_default_instance_;
class ServerStats;
class ServerStatsDefaultTypeInternal;
extern ServerStatsDefaultTypeInternal _ServerStats_default_instance_;
class ServerStatus;
class ServerStatusDefaultTypeInternal;
extern ServerStatusDefaultTypeInternal _ServerStatus_default_instance_;
class SimpleRequest;
class SimpleRequestDefaultTypeInternal;
extern SimpleRequestDefaultTypeInternal _SimpleRequest_default_instance_;
class SimpleResponse;
class SimpleResponseDefaultTypeInternal;
extern SimpleResponseDefaultTypeInternal _SimpleResponse_default_instance_;
class StreamingInputCallRequest;
class StreamingInputCallRequestDefaultTypeInternal;
extern StreamingInputCallRequestDefaultTypeInternal _StreamingInputCallRequest_default_instance_;
class StreamingInputCallResponse;
class StreamingInputCallResponseDefaultTypeInternal;
extern StreamingInputCallResponseDefaultTypeInternal _StreamingInputCallResponse_default_instance_;
class StreamingOutputCallRequest;
class StreamingOutputCallRequestDefaultTypeInternal;
extern StreamingOutputCallRequestDefaultTypeInternal _StreamingOutputCallRequest_default_instance_;
class StreamingOutputCallResponse;
class StreamingOutputCallResponseDefaultTypeInternal;
extern StreamingOutputCallResponseDefaultTypeInternal _StreamingOutputCallResponse_default_instance_;
class Void;
class VoidDefaultTypeInternal;
extern VoidDefaultTypeInternal _Void_default_instance_;
}  // namespace testing
}  // namespace grpc

namespace grpc {
namespace testing {

namespace protobuf_src_2fproto_2fgrpc_2ftesting_2fservices_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_src_2fproto_2fgrpc_2ftesting_2fservices_2eproto

// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace testing
}  // namespace grpc

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_2fproto_2fgrpc_2ftesting_2fservices_2eproto__INCLUDED
