// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: src/proto/grpc/testing/duplicate/echo_duplicate.proto

#include "src/proto/grpc/testing/duplicate/echo_duplicate.pb.h"
#include "src/proto/grpc/testing/duplicate/echo_duplicate.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace grpc {
namespace testing {
namespace duplicate {

static const char* EchoTestService_method_names[] = {
  "/grpc.testing.duplicate.EchoTestService/Echo",
  "/grpc.testing.duplicate.EchoTestService/ResponseStream",
};

std::unique_ptr< EchoTestService::Stub> EchoTestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< EchoTestService::Stub> stub(new EchoTestService::Stub(channel));
  return stub;
}

EchoTestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Echo_(EchoTestService_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResponseStream_(EchoTestService_method_names[1], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status EchoTestService::Stub::Echo(::grpc::ClientContext* context, const ::grpc::testing::EchoRequest& request, ::grpc::testing::EchoResponse* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Echo_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::grpc::testing::EchoResponse>* EchoTestService::Stub::AsyncEchoRaw(::grpc::ClientContext* context, const ::grpc::testing::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::ClientAsyncResponseReader< ::grpc::testing::EchoResponse>::Create(channel_.get(), cq, rpcmethod_Echo_, context, request);
}

::grpc::ClientReader< ::grpc::testing::EchoResponse>* EchoTestService::Stub::ResponseStreamRaw(::grpc::ClientContext* context, const ::grpc::testing::EchoRequest& request) {
  return new ::grpc::ClientReader< ::grpc::testing::EchoResponse>(channel_.get(), rpcmethod_ResponseStream_, context, request);
}

::grpc::ClientAsyncReader< ::grpc::testing::EchoResponse>* EchoTestService::Stub::AsyncResponseStreamRaw(::grpc::ClientContext* context, const ::grpc::testing::EchoRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::ClientAsyncReader< ::grpc::testing::EchoResponse>::Create(channel_.get(), cq, rpcmethod_ResponseStream_, context, request, tag);
}

EchoTestService::Service::Service() {
  AddMethod(new ::grpc::RpcServiceMethod(
      EchoTestService_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< EchoTestService::Service, ::grpc::testing::EchoRequest, ::grpc::testing::EchoResponse>(
          std::mem_fn(&EchoTestService::Service::Echo), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      EchoTestService_method_names[1],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< EchoTestService::Service, ::grpc::testing::EchoRequest, ::grpc::testing::EchoResponse>(
          std::mem_fn(&EchoTestService::Service::ResponseStream), this)));
}

EchoTestService::Service::~Service() {
}

::grpc::Status EchoTestService::Service::Echo(::grpc::ServerContext* context, const ::grpc::testing::EchoRequest* request, ::grpc::testing::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EchoTestService::Service::ResponseStream(::grpc::ServerContext* context, const ::grpc::testing::EchoRequest* request, ::grpc::ServerWriter< ::grpc::testing::EchoResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc
}  // namespace testing
}  // namespace duplicate

